package GUIAdminPanels;

public class AddTicketTypePanel extends JTemplates.PanelWithSetup {

    /**
     * Creates new form AddTicketTypePanel
     */
    public AddTicketTypePanel() {
        initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ticketNameLabel = new javax.swing.JLabel();
        ticketPriceLabel = new javax.swing.JLabel();
        ticketNameField = new javax.swing.JTextField();
        ticketPriceField = new javax.swing.JTextField();
        addTicketTypeButton = new javax.swing.JButton();

        ticketNameLabel.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        ticketNameLabel.setText("Ticket Name:");

        ticketPriceLabel.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        ticketPriceLabel.setText("Ticket Price:");

        ticketNameField.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        ticketNameField.setText("Ticketname");

        ticketPriceField.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        ticketPriceField.setText("25");

        addTicketTypeButton.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        addTicketTypeButton.setText("Add");
        addTicketTypeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTicketTypeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(ticketNameLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ticketPriceLabel)
                                .addGap(27, 27, 27)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ticketPriceField)
                            .addComponent(ticketNameField)))
                    .addComponent(addTicketTypeButton))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ticketNameLabel)
                    .addComponent(ticketNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ticketPriceLabel)
                    .addComponent(ticketPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addTicketTypeButton)
                .addContainerGap(161, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addTicketTypeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTicketTypeButtonActionPerformed
        TM.addTicketType(ticketNameField.getText(), Integer.valueOf(ticketPriceField.getText()));
        m.updateTicketTypeComboBox();
        m.update();
    }//GEN-LAST:event_addTicketTypeButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addTicketTypeButton;
    private javax.swing.JTextField ticketNameField;
    private javax.swing.JLabel ticketNameLabel;
    private javax.swing.JTextField ticketPriceField;
    private javax.swing.JLabel ticketPriceLabel;
    // End of variables declaration//GEN-END:variables
}
