package GUIAdminPanels;

public class RemoveTicketPanel extends JTemplates.PanelWithSetup {

    /**
     * Creates new form RemoveTicketPanel
     */
    public RemoveTicketPanel() {
        initComponents();
    }

    @Override
    public void update() {
        adminTicketTypeList.setModel(TM.getDefaultListModelTicketTypeList());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        adminTicketTypeList = new javax.swing.JList<>();
        adminRemoveTicketTypeButton = new javax.swing.JButton();

        adminTicketTypeList.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        adminTicketTypeList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(adminTicketTypeList);

        adminRemoveTicketTypeButton.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        adminRemoveTicketTypeButton.setText("Remove Ticket Type");
        adminRemoveTicketTypeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminRemoveTicketTypeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(adminRemoveTicketTypeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(adminRemoveTicketTypeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void adminRemoveTicketTypeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminRemoveTicketTypeButtonActionPerformed
        if (adminTicketTypeList.getSelectedIndex() != -1) {
            TM.removeTicketType(adminTicketTypeList.getSelectedIndex());
            adminTicketTypeList.setModel(TM.getDefaultListModelTicketTypeList());
        }
        m.update();
        m.updateTicketTypeComboBox();
    }//GEN-LAST:event_adminRemoveTicketTypeButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminRemoveTicketTypeButton;
    private javax.swing.JList<String> adminTicketTypeList;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
