package GUIMain;

import JTemplates.PanelWithSetup;
import Logic.Ticketmachine;
import Main.Main;
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;

public class CartPaymentPanel extends PanelWithSetup {

    /**
     * Creates new form CartPanel
     */
    public CartPaymentPanel() {
        initComponents();
    }

    @Override
    public void setup(Ticketmachine TM, Main main) {
        this.TM = TM;
        this.m = main;
        update();
        updateCartPaymentPanelTicketTypeComboBox();
    }

    @Override
    public void update() {
        cartList.setModel(TM.getDefaultListModelTicketList());
        ticketPriceLabel.setText("Ticket Price: " + String.valueOf(TM.getTicketPrice(ticketTypeComboBox.getSelectedIndex(), zoneComboBox.getSelectedIndex())));
        totalPriceLabel.setText("Total Price: " + String.valueOf(TM.getTicketListPrice()));
        balanceLabel.setText("Balance: " + String.valueOf(TM.getBalance()));
        if (TM.getTicketListPrice() > TM.getBalance()) {
            payWithCashButton.setEnabled(false);
        } else {
            payWithCashButton.setEnabled(true);
        }
    }

    public void updateCartPaymentPanelTicketTypeComboBox() {
        ticketTypeComboBox.setModel(TM.getDefaultComboBoxModelTicketTypeList());
    }

    @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g); // super fordi den arver fra JPanel class og paintComponent så den kan udskrive rigtigt på alle computere. 

        Graphics2D g2D = (Graphics2D) g;
       // AffineTransform original = g2.getTransform();
       g2D.setRenderingHint( // sæt tegnevink til trappeudjævning (antialias)
			RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        
        g2D.setColor(Color.BLUE);
        g2D.fillOval(10, 450, 680, 235);

        g.setColor(Color.CYAN);
        Font font = g.getFont().deriveFont(52.0f);
        g.setFont(font);
        g.drawString("JOMANI AWAY", 170, 580);

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        payWithCashButton = new javax.swing.JButton();
        ticketTypeComboBox = new javax.swing.JComboBox<>();
        zoneComboBox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        cartList = new javax.swing.JList<>();
        ticketPriceLabel = new javax.swing.JLabel();
        totalPriceLabel = new javax.swing.JLabel();
        balanceLabel = new javax.swing.JLabel();
        payWithCard = new javax.swing.JButton();
        addCash = new javax.swing.JButton();
        addCash1 = new javax.swing.JButton();
        addCash2 = new javax.swing.JButton();
        addCash3 = new javax.swing.JButton();
        addCash4 = new javax.swing.JButton();
        addCash5 = new javax.swing.JButton();
        addCash6 = new javax.swing.JButton();
        addCash7 = new javax.swing.JButton();
        addCash8 = new javax.swing.JButton();
        addCash9 = new javax.swing.JButton();
        addCash11 = new javax.swing.JButton();
        addTicketButton = new javax.swing.JButton();
        removeTicketButton = new javax.swing.JButton();
        emptyCartButton = new javax.swing.JButton();
        refundButton = new javax.swing.JButton();
        toLoginButton = new javax.swing.JButton();

        payWithCashButton.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        payWithCashButton.setText("Pay With Cash");
        payWithCashButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payWithCashButtonActionPerformed(evt);
            }
        });

        ticketTypeComboBox.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        ticketTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ticketTypeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ticketTypeComboBoxActionPerformed(evt);
            }
        });

        zoneComboBox.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        zoneComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Zone 1", "Zone 2", "Zone 3", "Zone 4", "Zone 5", "Zone 6" }));
        zoneComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zoneComboBoxActionPerformed(evt);
            }
        });

        cartList.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        cartList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(cartList);

        ticketPriceLabel.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        ticketPriceLabel.setText("jLabel1");

        totalPriceLabel.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        totalPriceLabel.setText("jLabel1");

        balanceLabel.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        balanceLabel.setText("jLabel1");

        payWithCard.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        payWithCard.setText("Pay with Card");
        payWithCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payWithCardActionPerformed(evt);
            }
        });

        addCash.setBackground(new java.awt.Color(153, 153, 153));
        addCash.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        addCash.setText("0.5");
        addCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCashActionPerformed(evt);
            }
        });

        addCash1.setBackground(new java.awt.Color(153, 153, 153));
        addCash1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        addCash1.setText("100");
        addCash1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCash1ActionPerformed(evt);
            }
        });

        addCash2.setBackground(new java.awt.Color(153, 153, 153));
        addCash2.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        addCash2.setText("50");
        addCash2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCash2ActionPerformed(evt);
            }
        });

        addCash3.setBackground(new java.awt.Color(153, 153, 153));
        addCash3.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        addCash3.setText("1");
        addCash3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCash3ActionPerformed(evt);
            }
        });

        addCash4.setBackground(new java.awt.Color(153, 153, 153));
        addCash4.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        addCash4.setText("1000");
        addCash4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCash4ActionPerformed(evt);
            }
        });

        addCash5.setBackground(new java.awt.Color(153, 153, 153));
        addCash5.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        addCash5.setText("2");
        addCash5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCash5ActionPerformed(evt);
            }
        });

        addCash6.setBackground(new java.awt.Color(153, 153, 153));
        addCash6.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        addCash6.setText("5");
        addCash6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCash6ActionPerformed(evt);
            }
        });

        addCash7.setBackground(new java.awt.Color(153, 153, 153));
        addCash7.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        addCash7.setText("10");
        addCash7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCash7ActionPerformed(evt);
            }
        });

        addCash8.setBackground(new java.awt.Color(153, 153, 153));
        addCash8.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        addCash8.setText("20");
        addCash8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCash8ActionPerformed(evt);
            }
        });

        addCash9.setBackground(new java.awt.Color(153, 153, 153));
        addCash9.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        addCash9.setText("200");
        addCash9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCash9ActionPerformed(evt);
            }
        });

        addCash11.setBackground(new java.awt.Color(153, 153, 153));
        addCash11.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        addCash11.setText("500");
        addCash11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCash11ActionPerformed(evt);
            }
        });

        addTicketButton.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        addTicketButton.setText("Add Ticket");
        addTicketButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTicketButtonActionPerformed(evt);
            }
        });

        removeTicketButton.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        removeTicketButton.setText("Remove Ticket");
        removeTicketButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeTicketButtonActionPerformed(evt);
            }
        });

        emptyCartButton.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        emptyCartButton.setText("Empty Cart");
        emptyCartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emptyCartButtonActionPerformed(evt);
            }
        });

        refundButton.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        refundButton.setText("Refund");
        refundButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refundButtonActionPerformed(evt);
            }
        });

        toLoginButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIMain/images/gears.jpg"))); // NOI18N
        toLoginButton.setText("jButton1");
        toLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toLoginButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ticketPriceLabel)
                    .addComponent(totalPriceLabel)
                    .addComponent(balanceLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ticketTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(zoneComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addTicketButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(removeTicketButton))
                    .addComponent(emptyCartButton)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(payWithCashButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(payWithCard)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(refundButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addCash)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addCash3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addCash5))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addCash1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addCash9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addCash11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addCash4))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addCash6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addCash7)
                        .addGap(18, 18, 18)
                        .addComponent(addCash8)
                        .addGap(18, 18, 18)
                        .addComponent(addCash2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(toLoginButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ticketTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(zoneComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ticketPriceLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totalPriceLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(balanceLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addTicketButton)
                            .addComponent(removeTicketButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emptyCartButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(payWithCashButton)
                            .addComponent(payWithCard)
                            .addComponent(refundButton))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addCash)
                            .addComponent(addCash3)
                            .addComponent(addCash5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addCash2)
                            .addComponent(addCash8)
                            .addComponent(addCash7)
                            .addComponent(addCash6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addCash4)
                            .addComponent(addCash11)
                            .addComponent(addCash9)
                            .addComponent(addCash1))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(toLoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ticketTypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ticketTypeComboBoxActionPerformed
        m.update();
    }//GEN-LAST:event_ticketTypeComboBoxActionPerformed

    private void zoneComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zoneComboBoxActionPerformed
        m.update();
    }//GEN-LAST:event_zoneComboBoxActionPerformed

    private void payWithCashButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payWithCashButtonActionPerformed
        TM.payWithBalance();
        m.update();
    }//GEN-LAST:event_payWithCashButtonActionPerformed

    private void payWithCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payWithCardActionPerformed
        TM.payWithCard();
        m.update();
    }//GEN-LAST:event_payWithCardActionPerformed

    private void addCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCashActionPerformed
        TM.addToBalance(0.5);
        m.update();
    }//GEN-LAST:event_addCashActionPerformed

    private void addCash3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCash3ActionPerformed
        TM.addToBalance(1);
        m.update();
    }//GEN-LAST:event_addCash3ActionPerformed

    private void addCash5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCash5ActionPerformed
        TM.addToBalance(2);
        m.update();
    }//GEN-LAST:event_addCash5ActionPerformed

    private void addCash6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCash6ActionPerformed
        TM.addToBalance(5);
        m.update();
    }//GEN-LAST:event_addCash6ActionPerformed

    private void addCash7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCash7ActionPerformed
        TM.addToBalance(10);
        m.update();
    }//GEN-LAST:event_addCash7ActionPerformed

    private void addCash8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCash8ActionPerformed
        TM.addToBalance(20);
        m.update();
    }//GEN-LAST:event_addCash8ActionPerformed

    private void addCash2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCash2ActionPerformed
        TM.addToBalance(50);
        m.update();
    }//GEN-LAST:event_addCash2ActionPerformed

    private void addCash1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCash1ActionPerformed
        TM.addToBalance(100);
        m.update();
    }//GEN-LAST:event_addCash1ActionPerformed

    private void addCash9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCash9ActionPerformed
        TM.addToBalance(200);
        m.update();
    }//GEN-LAST:event_addCash9ActionPerformed

    private void addCash11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCash11ActionPerformed
        TM.addToBalance(500);
        m.update();
    }//GEN-LAST:event_addCash11ActionPerformed

    private void addCash4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCash4ActionPerformed
        TM.addToBalance(1000);
        m.update();
    }//GEN-LAST:event_addCash4ActionPerformed

    private void addTicketButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTicketButtonActionPerformed
        TM.addTicketToTicketList(ticketTypeComboBox.getSelectedIndex(), zoneComboBox.getSelectedIndex() + 1);
        m.update();
    }//GEN-LAST:event_addTicketButtonActionPerformed

    private void removeTicketButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeTicketButtonActionPerformed
        if (cartList.getSelectedIndex() != -1) {
            TM.removeTicketFromTicketList(cartList.getSelectedIndex());
        }
        m.update();
    }//GEN-LAST:event_removeTicketButtonActionPerformed

    private void emptyCartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emptyCartButtonActionPerformed
        TM.removeAllTicketsFromTicketList();
        m.update();
    }//GEN-LAST:event_emptyCartButtonActionPerformed

    private void refundButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refundButtonActionPerformed
        TM.refund();
        m.update();
    }//GEN-LAST:event_refundButtonActionPerformed

    private void toLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toLoginButtonActionPerformed
        m.setTab(1);
    }//GEN-LAST:event_toLoginButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCash;
    private javax.swing.JButton addCash1;
    private javax.swing.JButton addCash11;
    private javax.swing.JButton addCash2;
    private javax.swing.JButton addCash3;
    private javax.swing.JButton addCash4;
    private javax.swing.JButton addCash5;
    private javax.swing.JButton addCash6;
    private javax.swing.JButton addCash7;
    private javax.swing.JButton addCash8;
    private javax.swing.JButton addCash9;
    private javax.swing.JButton addTicketButton;
    private javax.swing.JLabel balanceLabel;
    private javax.swing.JList<String> cartList;
    private javax.swing.JButton emptyCartButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton payWithCard;
    private javax.swing.JButton payWithCashButton;
    private javax.swing.JButton refundButton;
    private javax.swing.JButton removeTicketButton;
    private javax.swing.JLabel ticketPriceLabel;
    private javax.swing.JComboBox<String> ticketTypeComboBox;
    private javax.swing.JButton toLoginButton;
    private javax.swing.JLabel totalPriceLabel;
    private javax.swing.JComboBox<String> zoneComboBox;
    // End of variables declaration//GEN-END:variables
}
