package GUIMain;

import JTemplates.PanelWithSetup;
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;

public class LoginPanel extends PanelWithSetup {

    @Override
    public void update() {
        adminStateLabel.setText("Admin State: " + String.valueOf(TM.isAdminState()));
        if (!TM.isAdminState()) {
            loginButton.setText("Login");
        } else {
            loginButton.setText("Logout");
        }
    }

    /**
     * Creates new form LoginPanel
     */
    public LoginPanel() {
        initComponents();
    }

    @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g); // super fordi den arver fra JPanel class og paintComponent så den kan udskrive rigtigt på alle computere. 

        
        Graphics2D g2D = (Graphics2D) g;
       // AffineTransform original = g2.getTransform();
       g2D.setRenderingHint( // sæt tegnevink til trappeudjævning (antialias)
			RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2D.setColor(Color.BLUE);
        g2D.fillOval(610, 10, 680, 235);
        

        g.setColor(Color.CYAN);
        Font font = g.getFont().deriveFont(52.0f);
        g.setFont(font);
        g.drawString("JOMANI AWAY", 770, 130);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PasswordField = new javax.swing.JPasswordField();
        passwordLabel = new javax.swing.JLabel();
        loginButton = new javax.swing.JButton();
        adminStateLabel = new javax.swing.JLabel();
        adminImage = new javax.swing.JLabel();
        backToCartButton = new javax.swing.JButton();

        PasswordField.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        PasswordField.setText("1234");

        passwordLabel.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        passwordLabel.setText("Enter Password");

        loginButton.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        adminStateLabel.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        adminStateLabel.setText("Adminstate");

        adminImage.setBackground(new java.awt.Color(0, 0, 0));
        adminImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIMain/images/admin.png"))); // NOI18N
        adminImage.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        adminImage.setMaximumSize(new java.awt.Dimension(912, 912));

        backToCartButton.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        backToCartButton.setText("Back to cart");
        backToCartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToCartButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(PasswordField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(loginButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(backToCartButton))
                            .addComponent(passwordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(adminStateLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addComponent(adminImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 673, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(passwordLabel)
                .addGap(18, 18, 18)
                .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginButton)
                    .addComponent(backToCartButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(adminStateLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(adminImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        if (TM.isAdminState()) {
            TM.setAdminState(false);
            
        } else {
            TM.enableAdmin(PasswordField.getText()); 
        } m.update();
       
        
    }//GEN-LAST:event_loginButtonActionPerformed

    private void backToCartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToCartButtonActionPerformed
        m.setTab(0);
    }//GEN-LAST:event_backToCartButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JLabel adminImage;
    private javax.swing.JLabel adminStateLabel;
    private javax.swing.JButton backToCartButton;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel passwordLabel;
    // End of variables declaration//GEN-END:variables
}
