package JTemplates;

import Main.Main;
import Logic.Ticketmachine;

public class PanelWithSetup extends javax.swing.JPanel {

    /**
     * Creates variables of types Ticketmachine and Main.
     */
    public Ticketmachine TM;
    public Main m;

    /**
     * This panel gets setup with a reference to a Ticketmachine and Main object, which is created in Main
     * Main Frame has a different setup methods which calls this setup function on its panels and those panels
     * can contain underpanels, which are also subclasses of this object and therefore all panels uses the same ticketmachine
     * from main.
     * @param TM
     * @param main 
     */
    public void setup(Ticketmachine TM, Main main) {
        this.TM = TM;
        this.m = main;
        update();
    }
    
    public void update() {
        
    }
    
    /**
     * Creates new form PanelWithSetup
     */
    public PanelWithSetup() {
        initComponents();
    }
    
    public PanelWithSetup( String titel ){
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
