package Main;

import JTemplates.PanelWithSetup;

public final class Main extends javax.swing.JFrame {

    /**
     * Creates two variables of type Ticketmachine and Main.
     */
    Logic.Ticketmachine TM;
    Main M;

    /**
     * Gives a reference to this Ticketmachine and Main object.
     * So all the panels uses the same instance.
     * @param TM
     */
    public void setup(Logic.Ticketmachine TM) {
        cartPaymentPanel1.setup(TM, M);
        loginPanel1.setup(TM, M);
        adminPanel1.setup(TM, M);
    }

    /**
     * Creates new form Main
     */
    public Main() {
       this.setUndecorated(true);
        M = this;
        TM = new Logic.Ticketmachine();
        initComponents();
        setup(TM);
        update();
        
    }
    
    public void setTab( int tab){
        Tab.setSelectedIndex(tab);
    }

    /**
     * Calls the panels' update method.
     */
    public void update() {
        cartPaymentPanel1.update();
        loginPanel1.update();
        adminPanel1.update();
        if (!TM.isAdminState()) 
            Tab.setEnabledAt(2, false);
        else 
            Tab.setEnabledAt(2, true);
    }

    /**
     * Updates the Combobox in the CartPaymentPanel, used when tickettypes are added or removed.
     */
    public void updateTicketTypeComboBox() {
        cartPaymentPanel1.updateCartPaymentPanelTicketTypeComboBox();
        PanelWithSetup xxxx = new PanelWithSetup("Jacob");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Tab = new javax.swing.JTabbedPane();
        cartPaymentPanel1 = new GUIMain.CartPaymentPanel();
        loginPanel1 = new GUIMain.LoginPanel();
        adminPanel1 = new GUIMain.AdminPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Tab.addTab("Cart & Payment", cartPaymentPanel1);
        Tab.addTab("Login", loginPanel1);
        Tab.addTab("Admin", adminPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Tab, javax.swing.GroupLayout.DEFAULT_SIZE, 1698, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Tab, javax.swing.GroupLayout.DEFAULT_SIZE, 941, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            Main main = new Main();
            main.setExtendedState(MAXIMIZED_BOTH);

            main.setVisible(true);
            System.out.println("teste");
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Tab;
    private GUIMain.AdminPanel adminPanel1;
    private GUIMain.CartPaymentPanel cartPaymentPanel1;
    private GUIMain.LoginPanel loginPanel1;
    // End of variables declaration//GEN-END:variables
}
